BoxLayoutCanvas:

<BoxLayoutCanvas>:
    orientation: "vertical"
    Button:
        text: "Press A"
        size_hint: 1, .5
        pos_hint: {"left": .25}
    
    Button:
        text: "Press B"
    
    Button:
        text: "Press C"


<RetroWidget>:
    Button:
        text: "Hello"
        size: 100, 60
        pos: 100, 100
    
    Button:
        text: "Hello World"
        size: 200, 60
        pos: 50, 20